apiVersion: v1
kind: Service
metadata:
  name: crm-web-service
  namespace: crm-app
  labels:
    app: crm-web
    tier: web
spec:
  type: LoadBalancer
  selector:
    app: crm-web
    tier: web
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

